apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: podinfo-availability
  namespace: default
spec:
  provider:
    type: datadog
    address: https://api.datadoghq.com
    secretRef:
      name: datadog
  query: |
    100 - (
      sum:heimdall.response.count{
        environment:dev,http.status_class:2xx
      }.as_count()
      /
      sum:heimdall.response.count{
        environment:dev
      }.as_count()
    ) * 100
